#%RAML 1.0 DataType
type: object
properties:
  airline: string
  flightID: string
  source: string
  destination: string
  departureDate: date-only
  departureTime: string
  class: string
  direct: string
  price: number