#%RAML 1.0 NamedExample

value:
  
  -
    provider: Ola
    carNum: DL-7A-4058
    modelName: Wagon R
    type: Hatch-Back
    source: DEL
    destination: MUM
    journeyDate: 2021-12-23
    departureTime: 18:00
    driverRating: 4.5 star
    price: 10000
  -
    provider: Uber
    carNum: MH-6B-4058
    modelName: TATA Indigo
    type: Sedan
    source: MUM
    destination: BLR
    journeyDate: 2021-12-28
    departureTime: 08:00
    driverRating: 4.8 star
    price: 15000
  