#%RAML 1.0 NamedExample
cabsPostInput:
  
  -
    Rider Name: Rahul Gupta
    Email: rahul.123@apisero.com
    Car Num: DL-7A-4058
    Source: Delhi
    Destination : Mumbai
    Journey Date : 2021-11-11
    Departure Time: 07:00