#%RAML 1.0 NamedExample
cabsPostOutput:

  -
    Message: Cab Booked Successfully !!
    Booking ID: CB 0110202
    Rider: Rahul Gupta
    Car Num: DL-7A-4058
    Source: DEL
    Destination: MUM
    Journey Date: 2021-11-11
    Departure time: 07:00