#%RAML 1.0 NamedExample
flightsPostInput:

  -
    Flight ID: 6E 7745
    Source: Delhi
    Destination : Mumbai
    DepartureDate : 2021-11-11
    Departure time: 07:00
    NoOfPassengers : 2
    PassengerName: ["Kush Daga","Rahul Gupta"]
    Email: rahul.123@apisero.com