#%RAML 1.0 NamedExample

value:
  
  -
    airline: Indigo
    flightID: 6E 7745
    source: DEL
    destination: BLR
    departureDate: 2021-11-11
    departureTime: 02:20    
    class: Economy
    direct: Non-Stop
    price: 4100
  -
    airline: Indigo
    flightID: 6E 8055
    source: MUM
    destination: BLR
    departureDate: 2021-10-11
    departureTime: 02:20    
    class: Business
    direct: 1-Stop
    price: 10000
  