#%RAML 1.0 NamedExample
hotelsPostInput:

  -
    Hotel ID: TJ 001
    City: Delhi
    Check In Date: 2021-11-11
    Check Out Date: 2021-11-12
    NoOfGuests: 2
    RoomType: Deluxe
    NoOfRooms: 1
    GuestName: "Kush Daga, Rahul Gupta"
    Email: rahul.123@apisero.com
