#%RAML 1.0 NamedExample
value:  
  -
    HotelID: TJ 001
    HotelName: Taj Vivanta
    City: Delhi
    Price: 5500
    RoomType: Deluxe
    Rating: 3 star
    Amenities: "Wifi, Breakfast, Zero-cancellation, Swimming Pool"

  -
    HotelID: TJ 002
    HotelName: Taj Palace
    City: Chennai
    Price: 15990
    RoomType: Deluxe
    Rating: 5 star
    Amenities: "Wifi, Breakfast, Swimming Pool"
