#%RAML 1.0 NamedExample
hotelsPostOutput:

  -
    Message: Hotel Booked Successfully!!!
    Guest: "Kush Daga, Rahul Gupta"
    Hotel ID: TJ 001
    Check In Date: 2021-11-11
    Check Out Date: 2021-11-12
    NoOfGuests: 2
    NoOfRooms: 1
    Room Type: Deluxe
